### ISSUE TITLE
Allow cadence of Snowflake copy to be configurable

### ISSUE THREAD

**Issue by ihasfrozen** [PostHog/snowflake-export-plugin#27]
Today, the export copies data into Snowflake every 10 minutes, using the [MAX_TIME](https://github.com/PostHog/snowflake-export-plugin/blob/c1e96cdfdb46c57d602737b9d35a6aae4f4fdf8f/index.ts#L619) constant. Could this value be made configurable, rather than hard-coded? 

We've been seeing elevated compute usage in Snowflake since enabling the plugin and would like to try reducing the cadence of the copy operation to see if it lowers compute usage.

I'd be happy to contribute a change to make it configurable if you think it's ok to do!

**Comment by Twixes** [comment]
Hey! We'd definitely accept a contribution making this configurable. :)
