### ISSUE TITLE
Add support for persons-on-events

### ISSUE THREAD

**Issue by guillaumelachaud** [PostHog/snowflake-export-plugin#42]
It is my understanding that since the Nov 02 [update](https://posthog.com/blog/persons-on-events), the data model has been updated:

The `Event` table now holds a `person_properties` column that is supposed to store all the information of the person associated with the event.

This column is currently missing in the Snowflake exports. Is adding support for this column in exports as simple as adding the column into the [generateCsv](https://github.com/PostHog/snowflake-export-plugin/blob/main/index.ts#L160) function or is it blocked by https://github.com/PostHog/posthog/issues/10192 ?

**Comment by xvello** [comment]
Closing as this plugin has been deprecated in favor of our [Snowflake destination for batch exports](https://posthog.com/docs/cdp/batch-exports/snowflake).

Joining person properties on exported events is in our 2024 roadmap for the new batch exports system.
